import type { Listing, LocationData } from './types';

export const LOCATIONS: LocationData = {
  "USA": {
    "Alabama": ["Birmingham", "Montgomery", "Mobile"],
    "Alaska": ["Anchorage", "Fairbanks", "Juneau"],
    "Arizona": ["Phoenix", "Tucson", "Mesa"],
    "Arkansas": ["Little Rock", "Fort Smith", "Fayetteville"],
    "California": ["Los Angeles", "San Diego", "San Jose", "San Francisco"],
    "Colorado": ["Denver", "Colorado Springs", "Aurora"],
    "Florida": ["Jacksonville", "Miami", "Tampa", "Orlando"],
    "Georgia": ["Atlanta", "Augusta", "Columbus"],
    "Illinois": ["Chicago", "Aurora", "Joliet"],
    "New York": ["New York City", "Buffalo", "Rochester", "Yonkers"],
    "Texas": ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth"],
    "Washington": ["Seattle", "Spokane", "Tacoma"],
  },
  "Canada": {
    "Alberta": ["Calgary", "Edmonton", "Red Deer"],
    "British Columbia": ["Vancouver", "Victoria", "Kelowna", "Abbotsford"],
    "Manitoba": ["Winnipeg", "Brandon"],
    "Nova Scotia": ["Halifax", "Sydney"],
    "Ontario": ["Toronto", "Ottawa", "Mississauga", "Hamilton", "London"],
    "Quebec": ["Montreal", "Quebec City", "Gatineau", "Laval"],
    "Saskatchewan": ["Saskatoon", "Regina"],
  },
  "UK": {
    "England": ["London", "Manchester", "Birmingham", "Liverpool", "Bristol", "Sheffield"],
    "Scotland": ["Glasgow", "Edinburgh", "Aberdeen", "Dundee"],
    "Wales": ["Cardiff", "Swansea", "Newport"],
    "Northern Ireland": ["Belfast", "Derry"],
  },
};

export const COUNTRIES = Object.keys(LOCATIONS);
export const LISTING_TYPES = ["gar", "carb", "vend", "service", "fl", "paint"];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 1,
    authorId: 2,
    title: "Vintage Garage Sale Extravaganza",
    description: "Discover hidden treasures! We have everything from antique furniture to retro clothing. Early birds get the best picks. Everything must go!",
    country: "USA",
    state: "California",
    city: "Los Angeles",
    type: "gar",
    location: { lat: 34.0522, lng: -118.2437 },
    createdAt: "2023-10-26T10:00:00Z",
    eventDate: "2024-08-10",
    eventTime: "09:00",
  },
  {
    id: 2,
    authorId: 2,
    title: "Expert Carburetor Tuning Service",
    description: "Get your classic car running smoothly. Over 20 years of experience in tuning and rebuilding all types of carburetors. Fast and reliable service.",
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
    type: "carb",
    location: { lat: 43.6532, lng: -79.3832 },
    createdAt: "2023-10-25T14:30:00Z",
    eventDate: "2024-09-01",
    eventTime: "10:00",
  },
  {
    id: 3,
    authorId: 3,
    title: "Healthy Snack Vending Machine",
    description: "Looking for a new home for our gently used vending machine. Perfect for offices, schools, or gyms. Fully functional and ready to be stocked.",
    country: "UK",
    state: "England",
    city: "London",
    type: "vend",
    location: { lat: 51.5074, lng: -0.1278 },
    createdAt: "2023-10-24T09:00:00Z",
    eventDate: "2024-07-25",
    eventTime: "12:00",
  },
  {
    id: 4,
    authorId: 3,
    title: "Professional Home Painting Service",
    description: "Transform your space with a fresh coat of paint. We offer interior and exterior painting services with a focus on quality and detail. Free estimates available.",
    country: "USA",
    state: "New York",
    city: "New York City",
    type: "paint",
    location: { lat: 40.7128, lng: -74.0060 },
    createdAt: "2023-10-23T11:00:00Z",
    eventDate: "2024-08-15",
    eventTime: "08:30",
  },
  {
    id: 5,
    authorId: 2,
    title: "Downtown Studio Apartment for Lease",
    description: "Bright and modern studio apartment in the heart of the city. Features hardwood floors, new appliances, and a stunning view. Available for immediate occupancy.",
    country: "Canada",
    state: "British Columbia",
    city: "Vancouver",
    type: "fl",
    location: { lat: 49.2827, lng: -123.1207 },
    createdAt: "2023-10-22T18:00:00Z",
    eventDate: "2024-08-01",
    eventTime: "14:00",
  },
   {
    id: 6,
    authorId: 1,
    title: "Mobile Car Detailing Service",
    description: "We come to you! Full interior and exterior detailing packages. Your car will look brand new. Book your appointment today.",
    country: "USA",
    state: "Texas",
    city: "Austin",
    type: "service",
    location: { lat: 30.2672, lng: -97.7431 },
    createdAt: "2023-10-28T12:00:00Z",
    eventDate: "2024-07-29",
    eventTime: "11:00",
  }
];
